name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: ${{ github.workspace }}/MUMPS_5.7.3/include
      MUMPS_LIB: ${{ github.workspace }}/MUMPS_5.7.3/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages + ensure gfortran is accessible
      run: |
        brew update
        brew install gcc openblas lapack cmake metis

        # Locate gfortran binary (e.g., gfortran-13) and add to PATH
        GFORTRAN_PATH=$(ls $(brew --prefix gcc)/bin/gfortran-* | head -n 1)
        echo "Found gfortran binary: $GFORTRAN_PATH"
        echo "PATH=$(dirname $GFORTRAN_PATH):$PATH" >> $GITHUB_ENV

    - name: Install MUMPS 5.7.3 (manual build)
      run: |
        curl -L https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.3.tar.gz -o MUMPS_5.7.3.tar.gz
        tar xzf MUMPS_5.7.3.tar.gz
        cd MUMPS_5.7.3
        cp Make.inc/Makefile.inc.generic.SEQ Makefile.inc

        OPENBLAS_DIR=$(brew --prefix openblas)
        METIS_DIR=$(brew --prefix metis)

        sed -i '' "
          s/^CC *=.*/CC = gcc/;
          s/^FC *=.*/FC = gfortran/;
          s/^FL *=.*/FL = gfortran/;
          s/^SCOTCHDIR *=.*//;
          s/^ISCOTCH *=.*//;
          s/^LSCOTCH *=.*//;
        " Makefile.inc

        echo "LIBBLAS = -L${OPENBLAS_DIR}/lib -lopenblas" >> Makefile.inc
        echo "LIBMETIS = -L${METIS_DIR}/lib -lmetis" >> Makefile.inc
        echo "IMETIS = -I${METIS_DIR}/include" >> Makefile.inc
        echo "OPTF = -fallow-argument-mismatch -O2" >> Makefile.inc

        make -j$(sysctl -n hw.ncpu) d z s c

        mkdir -p include lib
        cp include/*.h include/
        cp lib/*.a lib/
        cp libseq/libmpiseq.a lib/

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python setup.py build_ext --inplace
        pip install .

    - name: Run tests
      run: |
        python -c "import mumps4py; print(f'MUMPS4PY successfully imported from {mumps4py.__file__}')"
        mpiexec -n 1 pytest -v
