name: Test MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: EnvMacOS
        environment-file: tests/env_macOS.yml
        auto-activate-base: false
        conda-remove-defaults: "true"
        python-version: ${{ matrix.python-version }}

    - name: Build and Test mumps4py
      run: |
        export MUMPS_INC="$(conda info --base)/envs/EnvMacOS/include"
        export MUMPS_LIB="$(conda info --base)/envs/EnvMacOS/lib"
        export MUMPS_SOLVERS="dmumps,cmumps,zmumps,smumps"
        export DYLD_LIBRARY_PATH="$MUMPS_LIB:$DYLD_LIBRARY_PATH"
        pip install . -vv --global-option="build_ext" --global-option="--inplace"
        pytest ${{ github.workspace }}/tests
