name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: ${{ github.workspace }}/MUMPS_5.7.3/include
      MUMPS_LIB: ${{ github.workspace }}/MUMPS_5.7.3/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        brew update
        brew install open-mpi openblas lapack cmake metis libomp

    - name: Install MUMPS 5.7.3 (parallel + shared, no SCOTCH)
      run: |
        curl -L https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.3.tar.gz -o MUMPS_5.7.3.tar.gz
        tar xzf MUMPS_5.7.3.tar.gz
        cd MUMPS_5.7.3
        cp Make.inc/Makefile.inc.debian.PAR Makefile.inc

        OPENBLAS_DIR=$(brew --prefix openblas)
        METIS_DIR=$(brew --prefix metis)
        LIBOMP_DIR=$(brew --prefix libomp)

        # Remove SCOTCH from config
        sed -i '' '/^SCOTCH/d' Makefile.inc
        sed -i '' '/^ISCOTCH/d' Makefile.inc
        sed -i '' '/^LSCOTCH/d' Makefile.inc

        # Use mpicc/mpif90
        echo "CC = mpicc" >> Makefile.inc
        echo "FC = mpif90" >> Makefile.inc
        echo "FL = mpif90" >> Makefile.inc

        # OpenMP flags for Clang (macOS)
        echo "CFLAGS = -Xpreprocessor -fopenmp -I${LIBOMP_DIR}/include" >> Makefile.inc
        echo "LDFLAGS = -L${LIBOMP_DIR}/lib -lomp" >> Makefile.inc

        # Paths and flags
        echo "LIBBLAS = -L${OPENBLAS_DIR}/lib -lopenblas" >> Makefile.inc
        echo "LIBMETIS = -L${METIS_DIR}/lib -lmetis" >> Makefile.inc
        echo "IMETIS = -I${METIS_DIR}/include" >> Makefile.inc
        echo "OPTF = -fallow-argument-mismatch -O2" >> Makefile.inc
        echo "SONAMEOPT = " >> Makefile.inc

        make -j$(sysctl -n hw.ncpu) allshared

        mkdir -p include lib
        cp include/*.h include/
        cp *.mod include/ || true
        cp lib/*.a lib/ || true
        cp lib/*.dylib lib/ || true
        cp libseq/libmpiseq.a lib/

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python setup.py build_ext --inplace
        pip install .

    - name: Run tests
      run: |
        python -c "import mumps4py; print(f'MUMPS4PY successfully imported from {mumps4py.__file__}')"
        mpiexec -n 2 pytest -v
