name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: /usr/local/include
      MUMPS_LIB: /usr/local/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        brew update
        brew install gcc openblas lapack wget cmake python

    - name: Install METIS 5.1.0 from mirror
      run: |
        curl -L -o metis-5.1.0.tar.gz https://sourceforge.net/projects/openfoam-extend/files/foam-extend-3.0/ThirdParty/metis-5.1.0.tar.gz/download
        tar -xzf metis-5.1.0.tar.gz
        cd metis-5.1.0
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
        make -j$(sysctl -n hw.ncpu)
        make install
        cd ..

    - name: Install MUMPS 5.7.0 (COIN-OR)
      run: |
        curl -L -o mumps.tgz https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.0.tar.gz
        tar -xzf mumps.tgz
        cd MUMPS_5.7.0
        cp Make.inc/Makefile.inc.generic.SEQ Makefile.inc
        sed -i '' 's/^CC *=.*/CC = gcc/' Makefile.inc
        sed -i '' 's/^FC *=.*/FC = gfortran/' Makefile.inc
        sed -i '' 's/^FL *=.*/FL = gfortran/' Makefile.inc
        sed -i '' 's/^LIBSEQ *=.*/LIBSEQ = -lpthread/' Makefile.inc
        make -j$(sysctl -n hw.ncpu)
        make install
        cd ..

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python3 setup.py build_ext --inplace
        pip3 install .

    - name: Check mumps4py module
      run: python3 -c "import mumps4py; print(mumps4py.__file__)"

    - name: Run mumps4py tests
      run: mpiexec -n 2 pytest -v
