name: Test MacOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: EnvMacOS
        environment-file: tests/env_macOS.yml
        auto-activate-base: false
        conda-remove-defaults: "true"

    - name: Build and Test mumps4py
      run: |
        export MUMPS_INC="$(conda info --base)/envs/EnvMacOS/include"
        export MUMPS_LIB="$(conda info --base)/envs/EnvMacOS/lib"
        export MUMPS_SOLVERS="dmumps,cmumps,zmumps,smumps"
        export DYLD_LIBRARY_PATH="$MUMPS_LIB:$DYLD_LIBRARY_PATH"
        python setup.py build_ext --inplace
        pip install .
        pytest ${{ github.workspace }}/tests
        