name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: /usr/local/opt/brewsci-mumps/include
      MUMPS_LIB: /usr/local/opt/brewsci-mumps/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        brew update
        brew install gcc openblas lapack python cmake
        
        # Install METIS first from the main Homebrew repo
        brew install metis
        
        # Create a symlink for METIS to trick brewsci-mumps
        mkdir -p $(brew --prefix)/Cellar/metis/5.1.0
        ln -s $(brew --prefix metis) $(brew --prefix)/Cellar/metis/5.1.0
        
        # Install MUMPS from brewsci
        brew tap brewsci/num
        brew install brewsci-mumps
        
        # Create symlink to gfortran if needed
        if ! command -v gfortran &> /dev/null; then
          GFORTRAN_BIN=$(brew --prefix gcc)/bin/gfortran-$(brew list gcc | grep -oE '[0-9]+$' | head -1)
          sudo ln -s $GFORTRAN_BIN /usr/local/bin/gfortran
        fi

        which gfortran
        gfortran --version

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python setup.py build_ext --inplace
        pip install .

    - name: Check mumps4py module
      run: python -c "import mumps4py; print(mumps4py.__file__)"

    - name: Run mumps4py tests
      run: mpiexec -n 1 pytest -v
