name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: ${{ github.workspace }}/MUMPS_5.7.0/include
      MUMPS_LIB: ${{ github.workspace }}/MUMPS_5.7.0/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        brew update
        brew install gcc openblas lapack wget cmake python metis

        # Create symlink to gfortran if needed
        if ! command -v gfortran &> /dev/null; then
          GFORTRAN_BIN=$(brew --prefix gcc)/bin/gfortran-$(brew list gcc | grep -oE '[0-9]+$' | head -1)
          sudo ln -s $GFORTRAN_BIN /usr/local/bin/gfortran || true
        fi

        which gfortran
        gfortran --version

    - name: Install MUMPS 5.7.0 (COIN-OR)
      run: |
        curl -L -o mumps.tgz https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.0.tar.gz
        tar -xzf mumps.tgz
        cd MUMPS_5.7.0
        cp Make.inc/Makefile.inc.generic.SEQ Makefile.inc

        sed -i '' 's/^CC *=.*/CC = gcc/' Makefile.inc
        sed -i '' 's/^FC *=.*/FC = gfortran/' Makefile.inc
        sed -i '' 's/^FL *=.*/FL = gfortran/' Makefile.inc

        echo "LIBMETIS = -lmetis" >> Makefile.inc
        echo "IMETIS = -lmetis" >> Makefile.inc

        make -j$(sysctl -n hw.ncpu)
        mkdir -p lib include
        cp libseq/libseq.a lib/
        cp lib/*mumps*.a lib/ || true
        cp include/*.h include/ || true
        cd ..

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python3 setup.py build_ext --inplace
        pip3 install .

    - name: Check mumps4py module
      run: python3 -c "import mumps4py; print(mumps4py.__file__)"

    - name: Run mumps4py tests
      run: mpiexec -n 1 pytest -v
