name: CI MUMPS4PY (macOS)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-macos:
    runs-on: macos-latest

    env:
      MUMPS_SOLVERS: dmumps,zmumps,smumps,cmumps
      MUMPS_INC: ${{ github.workspace }}/MUMPS_5.7.0/include
      MUMPS_LIB: ${{ github.workspace }}/MUMPS_5.7.0/lib

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        brew update
        brew install gcc openblas lapack wget cmake python

    - name: Install METIS 5.1.0 from GitHub
      run: |
        curl -L -o metis-5.1.0.tar.gz https://github.com/xijunke/METIS-1/archive/refs/heads/master.tar.gz
        tar -xzf metis-5.1.0.tar.gz
        mv METIS-1-master metis-5.1.0
        cd metis-5.1.0
        cmake -S metis-5.1.0 -B metis-5.1.0/build -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/metis-install
        cmake --build metis-5.1.0/build --parallel
        cmake --install metis-5.1.0/build

    - name: Install MUMPS 5.7.0 (COIN-OR)
      run: |
        curl -L -o mumps.tgz https://coin-or-tools.github.io/ThirdParty-Mumps/MUMPS_5.7.0.tar.gz
        tar -xzf mumps.tgz
        cd MUMPS_5.7.0
        cp Make.inc/Makefile.inc.generic.SEQ Makefile.inc
        sed -i '' 's/^CC *=.*/CC = gcc/' Makefile.inc
        sed -i '' 's/^FC *=.*/FC = gfortran/' Makefile.inc
        sed -i '' 's/^FL *=.*/FL = gfortran/' Makefile.inc
        sed -i '' 's|^INCPAR *=.*|INCPAR = -I${{ github.workspace }}/metis-install/include|' Makefile.inc
        sed -i '' 's|^LIBPAR *=.*|LIBPAR = -L${{ github.workspace }}/metis-install/lib -lmetis|' Makefile.inc
        make -j$(sysctl -n hw.ncpu)
        mkdir -p lib include
        cp libseq/libseq.a lib/
        cp lib/*mumps*.a lib/ || true
        cp include/*.h include/ || true
        cd ..

    - name: Install Python packages
      run: |
        pip3 install --upgrade pip
        pip3 install numpy mpi4py cython pytest

    - name: Build mumps4py
      run: |
        python3 setup.py build_ext --inplace
        pip3 install .

    - name: Check mumps4py module
      run: python3 -c "import mumps4py; print(mumps4py.__file__)"

    - name: Run mumps4py tests
      run: mpiexec -n 2 pytest -v
