name: Test Ubuntu Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: EnvUbuntu
        environment-file: tests/env_ubuntu.yml
        auto-activate-base: false
        conda-remove-defaults: "true"

    - name: Build and Test mumps4py
      run: |
        export MUMPS_INC="$(conda info --base)/envs/EnvUbuntu/include"
        export MUMPS_LIB="$(conda info --base)/envs/EnvUbuntu/lib"
        export MUMPS_SOLVERS="dmumps,cmumps,zmumps,smumps"
        python setup.py build_ext --inplace
        pip install .
        pytest ${{ github.workspace }}/tests
        