name: Test Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: Envwindows
        environment-file: tests/env_windows.yml
        auto-activate-base: false
        conda-remove-defaults: "true"
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest

    - name: Build and Test mumps4py
      run: |
        $env:MUMPS_INC = Join-Path $env:CONDA_PREFIX 'Library\include'
        $env:MUMPS_LIB = Join-Path $env:CONDA_PREFIX 'Library\lib'
        $env:MUMPS_SOLVERS = 'dmumps,cmumps,zmumps,smumps'
        $env:PATH = "$env:PATH;$env:MUMPS_LIB"
        python setup.py build_ext --inplace --compiler=msvc
        pip install .
        pytest -q tests        