name: Test Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
        python-version: ["3.12"]
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: Envwindows
        environment-file: tests/env_windows.yml
        auto-activate-base: false
        conda-remove-defaults: "true"
    - name: Install compiler
      id: install_cc
      uses: rlalik/setup-cpp-compiler@master
      with:
        compiler: latest

    - name: Build and Test mumps4py
      run: |
        echo %CONDA_PREFIX%
        set MUMPS_INC=%CONDA_PREFIX%\Library\include
        set MUMPS_LIB=%CONDA_PREFIX%\Library\lib
        set MUMPS_SOLVERS=dmumps,cmumps,zmumps,smumps
        set PATH=%PATH%;%MUMPS_LIB%
        python setup.py build_ext --inplace
        pip install .
        pytest ${{ github.workspace }}/tests
        