name: CI MUMPS4PY (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    env:
      MUMPS_SOLVERS: dmumps
      MUMPS_ROOT: ${{ github.workspace }}\mumps
      MUMPS_INC: ${{ github.workspace }}\mumps\include
      MUMPS_LIB: ${{ github.workspace }}\mumps\lib

    steps:
    - name: Setup MSYS2 with required packages
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: |
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-lapack
          mingw-w64-x86_64-openblas
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-pip
          mingw-w64-x86_64-python-numpy
          mingw-w64-x86_64-python-scipy
          mingw-w64-x86_64-python-mpi4py
          mingw-w64-x86_64-msmpi

    - name: Add MSYS2 MinGW64 to PATH
      shell: bash
      run: |
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
        echo "C:/Program Files (x86)/Microsoft SDKs/MPI" >> $GITHUB_PATH

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and extract MUMPS
      shell: msys2 {0}
      run: |
        curl -L -o mumps.tgz http://mumps.enseeiht.fr/MUMPS_5.6.2.tar.gz
        tar -xf mumps.tgz
        mv MUMPS_5.6.2 mumps

    - name: Configure and build MUMPS with MSMPI
      shell: msys2 {0}
      run: |
        cd mumps
        cp Make.inc/Makefile.inc.generic Makefile.inc
        echo "LIBBLAS = -lopenblas" >> Makefile.inc
        echo "LIBLAPACK = -llapack" >> Makefile.inc
        echo "LPORDDIR = $(topdir)/PORD/lib/" >> Makefile.inc
        echo "IPORD = -lpord" >> Makefile.inc
        echo "LMETISDIR = " >> Makefile.inc
        echo "IMETIS = " >> Makefile.inc
        echo "SCOTCHDIR = " >> Makefile.inc
        echo "ISCOTCH = " >> Makefile.inc
        echo "CC = gcc" >> Makefile.inc
        echo "FC = gfortran" >> Makefile.inc
        echo "FL = gfortran" >> Makefile.inc
        echo "OPTF = -O3" >> Makefile.inc
        echo "OPTC = -O3" >> Makefile.inc
        mkdir -p lib include
        make all
        cp include/*.h include/
        cp lib/*.a lib/

    - name: Install Python dependencies
      shell: msys2 {0}
      run: |
        python -m pip install --upgrade pip
        pip install cython pytest

    - name: Build mumps4py
      shell: msys2 {0}
      run: |
        python setup.py build_ext --inplace
        pip install .

    - name: Check mumps4py module
      shell: msys2 {0}
      run: python -c "import mumps4py; print(mumps4py.__file__)"

    - name: Run mumps4py tests
      shell: msys2 {0}
      run: |
        mpiexec -n 2 pytest -v
